apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: nginx
          name: nginx
          resources:
            limits:
              cpu: "10m"
            requests:
              cpu: "10m"